version: '2.3'
services:
  # To run benchmark suite docker-compose run --rm php src/benchmark
  php:
    image: prooph/php:7.2-cli
    environment:
      DRIVER: "mariadb"
      MARIADB_USER: "dev"
      MARIADB_PASSWORD: "dev"
      MARIADB_HOST: "database"
      MARIADB_PORT: "3306"
      MARIADB_CHARSET: "utf8"
      MARIADB_DB: "event_store_tests"
    volumes:
      - "./:/app"
    #cpuset: phpcpuset
    #cpu_count: phpcpu_count
    #mem_limit: phpmem_limit
    #mem_reservation: phpmem_reservation

  database:
    image: mariadb:10.3
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "event_store_tests"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
    command: "--max_connections=2500 --innodb_buffer_pool_size=BUFFER_POOL_SIZE --query_cache_type=1 --query_cache_limit=256K --query_cache_min_res_unit=2k --query_cache_size=100M --tmp_table_size=64M --max_heap_table_size=64M --max_allowed_packet=256M"
    #cpuset: dbcpuset
    #cpu_count: dbcpu_count
    #mem_limit: dbmem_limit
    #mem_reservation: dbmem_reservation
